name: ThePVZ
options:
  bundleIdPrefix: com.esyle
  createIntermediateGroups: true
  deploymentTarget:
    iOS: '15.0'
settings:
  base:
    SWIFT_VERSION: '5.0'
    TARGETED_DEVICE_FAMILY: '1'
    MARKETING_VERSION: 1.0.0
    CURRENT_PROJECT_VERSION: '1'
    ARCHS: arm64
    ONLY_ACTIVE_ARCH: 'NO'
    SWIFT_STRICT_CONCURRENCY: minimal
    SWIFT_TREAT_WARNINGS_AS_ERRORS: 'NO'
    GCC_TREAT_WARNINGS_AS_ERRORS: 'NO'
    ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
targets:
  ThePVZ:
    type: application
    platform: iOS
    sources:
      - path: ThePVZ
        excludes: ['Resources/**']
      - path: ThePVZ/Resources
        type: folder
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.esyle.thepvz
        PRODUCT_NAME: ThePVZ
    info:
      path: Support/Info.plist
      properties:
        CFBundleDisplayName: The PVZ
        CFBundleSignature: '????'
        LSRequiresIPhoneOS: true
        UILaunchScreen: {}
        UIUserInterfaceStyle: Dark
        UIRequiresFullScreen: true
        UIStatusBarHidden: true
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
          UISceneConfigurations:
            UIWindowSceneSessionRoleApplication:
              - UISceneConfigurationName: Default Configuration
                UISceneDelegateClassName: $(PRODUCT_MODULE_NAME).SceneDelegate
        CADisableMinimumFrameDurationOnPhone: true
        UIFileSharingEnabled: true
        LSSupportsOpeningDocumentsInPlace: true
        ITSAppUsesNonExemptEncryption: false
  ThePVZTests:
    type: bundle.unit-test
    platform: iOS
    sources: [ThePVZTests]
    dependencies:
      - target: ThePVZ
schemes:
  ThePVZ:
    build:
      targets:
        ThePVZ: all
    test:
      targets: [ThePVZTests]
